name: 'Basic Terraform Workflow'

on: workflow_dispatch
    
jobs:
  terraform:
    name: 'Terraform Init, Plan, and Apply'
    runs-on: runner
    
    # Required for OIDC authentication
    permissions:
      id-token: write 
      contents: read 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    # 🔑 Authentication Step (using OIDC with Azure)
    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: "5490ace0-6dfb-48d2-840c-93e2b7241766"
        tenant-id: "de80a58f-1610-4908-a1a7-862be272a38c"
        subscription-id: "0f48ce1f-16d2-42ba-8b4f-0bef1a58b563"
        enable-AzPSSession: false

    # 🔧 Setup Terraform: KEEP THIS CLEAN, only install the CLI
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
      # 🚫 DO NOT add working-directory input here. The logs confirmed it's invalid.

    # 1. Initialize
    - name: Terraform Init
      # ⬅️ CORRECT WAY: Set the directory for THIS run step
      working-directory: environments/dev 
      run: terraform init

    # 2. Plan
    - name: Terraform Plan
      # ⬅️ CORRECT WAY: Set the directory for THIS run step
      working-directory: environments/dev
      run: terraform plan -no-color

    # 3. Apply
    - name: Terraform Apply
      # ⬅️ CORRECT WAY: Set the directory for THIS run step
      working-directory: environments/dev
      run: terraform apply -auto-approve
